version: "3.7"
services:
  koumei:
    # image: node:16.14
    build: koumei
    volumes:
      - type: bind
        source: d:/devenv/koumei
        target: /web
    tty: true
    entrypoint: ["bash"]
